version: '3.7'

services:
  react:
    image: genee-client
    container_name: genee-client
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000