version: '3.7'

services:
  nodejs:
    image: genee-server
    container_name: genee-server
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    ports:
      - "8080:8080"